website/__init__.py
from flask import Flask


def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'a507cf82d9cd01dcc897937bf985231c32eca78bd16efae7597519ddf982da57'

    from .views import views

    app.register_blueprint(views, url_prefix='/')
    
    return app

website/views.py
from flask import Blueprint, render_template


views = Blueprint('views', __name__)


@views.route("/")
def home():
    return render_template("home.html")

@views.route("/about")
def about():
    return render_template("about.html")

@views.route("/donate")
def donate():
    return render_template("donate.html")

@views.route("/tutors")
def tutors():
    return render_template("tutors.html")

@views.route("/volunteer")
def volunteer():
    return render_template("volunteer.html")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css')}}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&icon_names=function,group,groups,history_edu,laptop_mac" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <h3>S4S Tutoring</h3>
        <nav>
            <ul>
                <li><a href="index.html"><div class="header-link">Home</div></a></li>
                <li><a href="tutoring.html"><div class="header-link">Tutoring</div></a></li>
                <li><a href="volunteer.html"><div class="header-link">Volunteer</div></a></li>
                
                <li><a href="donate.html"><div class="header-link">Sign in</div></a></li>
            </ul>
            <a href="signup.html"><div class="signup-btn">Sign Up</div></a>
            
        
        
        </nav>
        
    </header>

    {% block content %}{% endblock %}

    <footer>
        <div class="footer-links">
            <ul>
                <li><a href="about.html"><div class="header-link">About</div></a></li>
                <li><a href="donate.html"><div class="header-link">Support us</div></a></li>
                <li><a href="about.html"><div class="header-link">Contact</div></a></li>
            </ul>
        </div>
        
        <h4>S4S Tutoring</h4>


    </footer>
</body>
</html>

templates/tutoring.html
{% extends 'base.html' %}

{% block title %}
Our Tutors
{% endblock %}

website/templates/about.html
{% extends 'base.html' %}

{% block title %}
About us
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css')}}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined&icon_names=function,group,groups,history_edu,laptop_mac" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <h3>S4S Tutoring</h3>
        <nav>
            <ul>
                <li><a href="{{ url_for('views.home') }}"><div class="header-link">Home</div></a></li>
                <li><a href="{{ url_for('views.tutors') }}"><div class="header-link">Tutoring</div></a></li>
                <li><a href="{{ url_for('views.volunteer') }}"><div class="header-link">Volunteer</div></a></li>
                <li><a href="{{ url_for('views.donate') }}"><div class="header-link">Sign in</div></a></li>
            </ul>
            <a href="signup.html"><div class="signup-btn">Sign Up</div></a>
            
        
        
        </nav>
        
    </header>

    {% block content %}{% endblock %}

    <footer>
        <div class="footer-links">
            <ul>
                <li><a href="about.html"><div class="header-link">About</div></a></li>
                <li><a href="donate.html"><div class="header-link">Support us</div></a></li>
                <li><a href="about.html"><div class="header-link">Contact</div></a></li>
            </ul>
        </div>
        
        <h4>S4S Tutoring</h4>


    </footer>
</body>
</html>

website/templates/donate.html
{% extends 'base.html' %}

{% block title %}
Donate
{% endblock %}

website/templates/home.html
{% extends 'base.html' %}

{% block title %}
Home Page
{% endblock %}

{% block content %}
<div class="hero-page">
    <h1>
        Students helping Students
    </h1>
    <h2>
        Academic assistance by the students, for the students
    </h2>

    <button class="find-tutors-btn">Find Peer Tutors</button>

    <div class="tutor-carousel">
        <div class="tutor-group">
            <div class="tutor-profile">
                <img src="" alt="">
                <h2>Caleb W</h2>
                <ul>
                    <li>SAT</li>
                    <li>AP WORLD</li>
                    <li>Calc AB</li>

                </ul>
            </div>
            <div class="tutor-profile">
                <img src="" alt="">
                <h2>Michael T</h2>
                <ul>
                    <li>PSAT</li>
                    <li>AP Lang</li>
                    <li>APUSH</li>

                </ul>
            </div>
            <div class="tutor-profile">
                <img src="" alt="">
                <h2>Ali S</h2>
                <ul>
                    <li>AP Seminar</li>
                    <li>AP WORLD</li>
                    <li>Pre-Calc</li>

                </ul>
            </div>
            <div class="tutor-profile">
                <img src="" alt="">
                <h2>Joe C</h2>
                <ul>
                    <li>AP Lit</li>
                    <li>AP Stat</li>
                    <li>Calc BC</li>

                </ul>
            </div>
            



        </div>

        <div aria-hidden class="tutor-group">
            <div class="tutor-profile">
                <img src="" alt="">
                <h2>Caleb W</h2>
                <ul>
                    <li>SAT</li>
                    <li>AP WORLD</li>
                    <li>Calc AB</li>

                </ul>
            </div>
            <div class="tutor-profile">
                <img src="" alt="">
                <h2>Michael T</h2>
                <ul>
                    <li>PSAT</li>
                    <li>AP Lang</li>
                    <li>APUSH</li>

                </ul>
            </div>
            <div class="tutor-profile">
                <img src="" alt="">
                <h2>Ali S</h2>
                <ul>
                    <li>AP Seminar</li>
                    <li>AP WORLD</li>
                    <li>Pre-Calc</li>

                </ul>
            </div>
            <div class="tutor-profile">
                <img src="" alt="">
                <h2>Joe C</h2>
                <ul>
                    <li>AP Lit</li>
                    <li>AP Stat</li>
                    <li>Calc BC</li>

                </ul>
            </div>


        </div>


    </div>

</div>
<div class="description">
    <h2>Quality Peer Tutoring for All Students</h2>
    <h3>Here at S4S Tutoring, we hope to make getting helpful, friendly help with school work as easy as possible</h3>
    <div class="icons-container">
        <div class="icon-container">
            <span class="material-symbols-outlined size-large">
            group
            </span>
            <h3>Connection</h3>
            <h4>Connect with peers who are willing to lend a hand</h4>
        </div>

        <div class="icon-container multi-icon">
            <span class="material-symbols-outlined size-small">
                function
            </span>
            <span class="material-symbols-outlined size-small indented">
                history_edu
            </span>
            <h3>Class-Oriented</h3>
            <h4>Get assistance from those who know your material best</h4>
        </div>

        <div class="icon-container multi-icon">
            <span class="material-symbols-outlined size-small">
                groups
            </span>
            <span class="material-symbols-outlined size-small indented">
                laptop_mac
            </span>
            <h3>Flexibility</h3>
            <h4>Meet with a peer-tutor in-person or online</h4>
        </div>
    </div>
  </div>

<div class="testimonial-container">
    <h2>Hear From Past Students</h2>
    <h3>All from real high school students</h3>
    
    <div class="testimonial">
        <img src="" alt="">
        <div class="testimonial-text">
            <h2>John Doe (10th)</h2>
            <p>"With the help of S4S Tutoring, I was able to get the help I needed with my AP Biology class.
             My tutor was very friendly and guided me through the class's material"
            </p>
        </div>
        


    </div>
    <div class="testimonial">
        <img src="" alt="">
        <div class="testimonial-text">
            <h2>Rex Ample (11th)</h2>
            <p>"I was really struggling in my Calculus class, so I though I'd try to reach out for assistance.
            I met a peer tutor on S4S Tutoring, and within seconds of meeting with him, I knew this was the right choice."
            </p>
        </div>
    </div>
    <div class="testimonial">
        <img src="" alt="">
        <div class="testimonial-text">
            <h2>Justa Test (9th)</h2>
            <p>"High school was definitely a bit of an adjustment for me. I felt that middle school didn't prepare me properly for the classes I was taking.
                 S4S Tutoring was a big help. I'd recommend it anyone."
            </p>
        </div>
        
    </div>
</div>
{% endblock%}

website/templates/login.html
{% extends 'base.html' %}

{% block title %}
Login
{% block end %}

website/templates/signup.html
{% extends 'base.html' %}

{% block title %}
Sign Up
{% endblock %}

website/templates/tutors.html
{% extends 'base.html' %}

{% block title %}
Our Tutors
{% endblock %}

{% block content %}
<div class="hero-page">
    <h1>Find a Tutor</h1>
    <h3>Check our Google Calendar for Availability</h3>
    <iframe src="https://calendar.google.com/calendar/embed?height=600&wkst=1&ctz=America%2FNew_York&showPrint=0&title=S4S%20Tutoring%20Session&showTitle=0&showCalendars=0&showTz=0&src=ZjMwMGNlMjExNGYwYTFmZGRlMzMzNjFjNzBjOWRiZTMyYmE3ZGMwY2UyYTQxM2JjODFiZjZkNTJhYWU3MTgyMkBncm91cC5jYWxlbmRhci5nb29nbGUuY29t&src=ZW4udXNhI2hvbGlkYXlAZ3JvdXAudi5jYWxlbmRhci5nb29nbGUuY29t&color=%23E4C441&color=%230B8043" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
</div>
{% endblock %}

website/templates/volunteer.html
{% extends 'base.html' %}

{% block title %}
Volunteer
{% endblock %}

{% block content %}
<div class="hero-page">
    <h1>Join S4S Today!</h1>
    <h3><em>become a tutor or work behind the scenes!</em></h3>
</div>
{% endblock %}